ctapipe_io_lst/__init__.py
ctapipe_io_lst/containers.py

In this PR I add the check of the flag that extdevices_presence flag (discovered only recently) that tells which devices are seen by the EvB. The R0  time and trigger are set with the following criteria: if UTCS is available its values are taken, otherwise the TIB values.
The timestamp is for the moment in ns (is it ok?)
I add also the unpacking go the SWAT data, even if they are empty of the moment.

Add criteria to decide from where to take timestamp and trigger valeus

---

ctapipe_io_lst/__init__.py

The method EventSource.subarray() is abstract in ctapipe v0.7. Without this definition, LSTEventSource can not be instantiated.

Defined the abstract method LSTEventSource.subarray().

---

README.md
ctapipe_io_lst/__init__.py
ctapipe_io_lst/version.py
setup.py

Add automatic version loading as in `ctapipe` and `cta-lstchain` with the `version.py` file

Add automatic version

---

.gitignore
ctapipe_io_lst/__init__.py
ctapipe_io_lst/tests/test_version.py
setup.py
version.py

* Add link to prozozfits reader (there is a newer version, do you want to still use 1.4.2?)
* Duplicate version.py so it can be used at runtime and at install time (a bit ugly, but works)
* Define OPTICS  instead of using `OpticsDescription.from_name`, so this works without ctapipe-extra

Fix pip install

---

ctapipe_io_lst/__init__.py

This PR fixes issue https://github.com/cta-observatory/ctapipe_io_lst/issues/25 adding missing provenance tracking for input files opened in several parts of the code. It also fixes the duplicated presence of a ``version.py`` file, and minor formatting aspects like import sorting or typos.

Add provenance tracking missing for input files

---

ctapipe_io_lst/__init__.py

This replaces the loop using struct to unpack a numpy array of bytes (uint8) with just using `view` to get the single arrays out of it.
In my test, this reduces the reading time for 10000 events from 20 to 16 seconds, so roughly a  20 % improvement.
The code is also much more readable and it preserves the correct data types (before it was converted to float64, which especially for the uint64 is not good!)
This is what I already mentioned here: #2

Replace struct loop with numpy.view and correct dtype

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/calibration.py

In order to use the new reader with the calibration tools it is useful to separate  low-level calibration from the high level (not used in the calibration tools) and to tag the flat-field events before the pe calibration.

Changes for calibration tools

---

ctapipe_io_lst/calibration.py

This fixes the bug discussed here: https://github.com/cta-observatory/cta-lstchain/issues/559
Before and after comparison:

Fix for lstchain#559

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_stage1.py

This is motivated by run 2006.0000, where after a UCTS trigger type
with value 42 the ucts trigger type seems to be shifted by one
without the UCTS time showing an offset.
Also adds  a warning if an event with UCTS trigger == 42 is encountered.

Use tib trigger if available by default

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/calibration.py
ctapipe_io_lst/event_time.py

- Add trailet in order not to calibrate pedestals and FF events if requested
- Correct "if"  statement  for exception in case of missing ucts info, which is often the case in old runs

Changes for interleaved events and old runs

---

ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_event_time.py

Columns will always have integer dtype where appropriate and where the fill contains `nan` these are converted to masked array elements.

Make sure dtype of night summary table is int for counters

---

.github/workflows/ci.yml
ctapipe_io_lst/__init__.py
ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_calib.py
ctapipe_io_lst/tests/test_event_time.py
ctapipe_io_lst/tests/test_lsteventsource.py
ctapipe_io_lst/tests/test_stage1.py

* Since times calculated based on the dragon counters are the most precise
and it is always possible to calculate them, there is no reason to use
TIB counters for time, so the option to calculate time based on TIB is
removed.
* If reference counters / timestamps for dragon time are not given,
the run start timestamp svc.date is used, which results in timestamps
being off by an unknown amount of seconds. These timestamps can
still be usefull for tracking relative times or interpolating
pointing, but not for precise event time stamps.

Remove option to calculate timestamp from TIB, allow using svc.date as reference

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/anyarray_dtypes.py
ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_event_time.py
ctapipe_io_lst/tests/test_stage1.py
example_stage1_config.json

This reads the run summary files as produced by https://github.com/cta-observatory/cta-lstchain/pull/614 .
This is ready to be reviewed, but I will put it in draft mode until that PR is merged.

Allow dragon reference values to be read from the RunSummary

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/tests/test_lsteventsource.py

Since the service container only depends on the `CameraConfiguration`, we can already fill it in `__init__` and expose it as a member of the source.
This will make it easier to deal with, for example like here in the PR for the pedestal fits writer:
https://github.com/cta-observatory/cta-lstchain/pull/601/

Expose service container at source

---

ctapipe_io_lst/calibration.py

continued from #92 
I changed a branch name just to avoid confusion.

Set zeros if R0 data is negative after the time lapse correction

---

ctapipe_io_lst/calibration.py
ctapipe_io_lst/tests/test_calib.py

Filling nans breaks the `GlobalPeakWindowSum` extractor used for muon events (And probably also all neighbors of nan pixels with the `NeighborPeakWindowSum`)

Fill 0 instead of nan for missing pixels

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_event_time.py

Because of numpy's type promotion rules and the dtypes involved, `dragon_time` was actually a float64, not uint64, loosing us precision, I don't know how important that loss of precision was though.
@rlopezcoto How important might this be for the pulsar analysis?

Fix dtype of dragon time, keep info about jumps

---

ctapipe_io_lst/calibration.py

This adds functions to obtain the positions of the spikes needed for calculating the spike heights to enable spike subtraction instead of interpolation and a function to update the last_readout_times needed to create the time calibration file in this lstchain PR here: https://github.com/cta-observatory/cta-lstchain/pull/725

Spike positions

---

ctapipe_io_lst/calibration.py

As discussed via slack, there is no "correct" default for these calib
scales since they depend on how the calibration was performed.
They have to be set appropriately in the config. A "sane" default is
thus to apply no calib scaling (e.g. both factors = 1.0)

Change default calib scales to unity

---

ctapipe_io_lst/calibration.py
ctapipe_io_lst/tests/test_calib.py
ctapipe_io_lst/tests/test_lsteventsource.py

This changes how the global offset subtraction is done in
ctapipe_io_lst.
Instead of subtracting `offset` from both the waveform and the drs4
pedestal, we now rely on the offset being part of the drs4 pedestal.
This means, that when the drs4 pedestal calibration is used, no offset
needs to be given, making it possible to analyze runs with different
offsets without adapting the configuration.

Do not subtract an offset by default

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/tests/test_calib.py
ctapipe_io_lst/tests/test_lsteventsource.py

This makes changes like was done to the drs4 calibration to the pointing information and trigger information.
Both are now by default true and it is required to give a drive report when requesting pointing information. This will lead to clearer errors when pointing info is needed and avoid the "No drive report given, pointing info will not be filled" warning in case no pointing information is required.

Add options for loading trigger and pointing info

---

ctapipe_io_lst/calibration.py
ctapipe_io_lst/tests/test_calib.py

An unintended side effect of relying on the drs4 offsets to also subtract the base offset of the waveform so that it does not have to be known is that now the waveform is already centered around 0 when applying the delta T correction.
The limit introduced here #95 thus now prevents any negative samples, biasing the pedestal estimation.
I see three options:
* Reintroduce the offset
* Remove the limit on the value that is subtracted from the waveform (done for now in this PR)
* Switch the order in which baseline and timelapse correction are applied, so that the waveform going into the timelapse correction is still around 400, not around 0.
Any opinions?

Fix biased r1 waveform after delta T correction

---

.github/workflows/ci.yml
ctapipe_io_lst/__init__.py
ctapipe_io_lst/calibration.py
ctapipe_io_lst/event_time.py
ctapipe_io_lst/pointing.py
ctapipe_io_lst/tests/test_stage1.py
environment.yml
setup.py

Small changes to make the source compatible with 0.12.
Let's discuss if we want to switch to 0.12 for the new lstchain version already or later.

Update ctapipe to 0.12

---

ctapipe_io_lst/__init__.py
ctapipe_io_lst/multifiles.py
ctapipe_io_lst/tests/test_lsteventsource.py
ctapipe_io_lst/tests/test_multifile.py

Rewrite MultiFiles to allow reading all subruns

---

ctapipe_io_lst/event_time.py
ctapipe_io_lst/tests/test_event_time.py

This fixes `time_from_unix_tai_ns` in case the input is not already an `np.uint64`, which was the case in `ctapipe_io_lst` but could easily not be the case if this function is imported somewhere else.
See this issue in `ctapipe_io_lst nectarcam` for more details:
https://github.com/cta-observatory/ctapipe_io_nectarcam/issues/24

Improve dtype handling in time_from_unix_tai_ns, improve test

---

ctapipe_io_lst/pointing.py
ctapipe_io_lst/tests/test_lsteventsource.py
ctapipe_io_lst/tests/test_pointing.py
ctapipe_io_lst/tests/test_stage1.py
example_stage1_config.json

This replaces using the old format with the new format.
@morcuended Heads-Up for osa, after this is released and used by lstchain, you will need to pass the `DrivePosition_log_<YYYYMMDD>.txt` files, not the `drive_position_log_YY_MM_DD.txt` files.
The `array_ra`, `array_dec` values are not filled anymore, they are not available from the files and didn't provide any further information since they were only transformed from the alt/az values.

Switch to using new drive report logs

---

.github/workflows/ci.yml
environment.yml
eventsource_subclasses.py
setup.cfg
src/ctapipe_io_lst/tests/test_calib.py
src/ctapipe_io_lst/tests/test_event_time.py
src/ctapipe_io_lst/tests/test_pointing.py
src/ctapipe_io_lst/tests/test_stage1.py

Basically no changes needed aside from making sure that the test data is given as absolute paths since ctapipe 0.18 now uses a tmp dir by default when using `run_tool`

Make source compatible with ctapipe 0.18, test with 0.17 and 0.18

---

src/ctapipe_io_lst/__init__.py

Check # of gains in FF events, and don't apply heuristic tag on 1-gain events.

Check # of gains in FF events. 

---

src/ctapipe_io_lst/__init__.py

Wrong reference location was being filled into the `SubarrayDescription`

Fix reference_location filled into SubarrayDescription

---

.github/workflows/ci.yml
setup.cfg
src/ctapipe_io_lst/__init__.py
src/ctapipe_io_lst/calibration.py
src/ctapipe_io_lst/evb_preprocessing.py
src/ctapipe_io_lst/multifiles.py
src/ctapipe_io_lst/tests/test_calib.py
src/ctapipe_io_lst/tests/test_cta_r1.py

Changes to make it fully work with EVBv6 data, not yet ready, will update as more test data is taken
Missing:

Ctar1 fixes

---

src/ctapipe_io_lst/__init__.py
src/ctapipe_io_lst/tests/test_calib.py

Always fill tels_with_trigger

---

src/ctapipe_io_lst/__init__.py

Fixes #206 
I checked with the run given, the broken pixels included in the data stream that were for some reason not DVRed are filled with 0 by the source, so all good I would say.

Perform broken pixels check only in case of non-dvred pixels

---

src/ctapipe_io_lst/__init__.py
src/ctapipe_io_lst/calibration.py

Fixes #227 
We do support reading reduced data in case we do not need to apply DRS4 corrections and we decided not to support the mixed case.
So I just added a clear error message for the unsupported case of trying to apply DRS4 corrections to data with removed samples.

Raise good error message in case border slices removed by EVB

---

.github/workflows/ci.yml
environment.yml
setup.cfg
src/ctapipe_io_lst/anyarray_dtypes.py

We fixed scipy here to an issue in ctapipe, but this is fixed in the latest version of ctapipe and it doesn't make sense to limit it here in the package metadata.

support ctapipe 0.22

---

src/ctapipe_io_lst/calibration.py
src/ctapipe_io_lst/tests/test_calib.py

This is necessary in order to move to fits output as requested by EvB

Add reading of  calibration files in fits format
