cta-observatory/ctapipe_io_lst

ctapipe_io_lst/__init__.py, ctapipe_io_lst/containers.py
Improved PedestalContainer data naming
=> Improved nomenclature

ctapipe_io_lst/__init__.py, ctapipe_io_lst/containers.py
- Added first version of the  WaveformCalibrationContainer which contain the waveform calibration coefficients 
- Improved the container description 
This PR must be approved before the last version of the calibration code can be PR
=> Calib containers

ctapipe_io_lst/__init__.py, ctapipe_io_lst/containers.py
This PR update the reader to the present version of ctapipe which now contains the calibration containers.
=> Make reader compatible with crappie

ctapipe_io_lst/__init__.py, ctapipe_io_lst/containers.py
In this PR I add a LSTMonitoringContainer meant to contain LST specific monitoring data.
In particular, the Pointing container that @labsasha prepared for the raw pointing information
=> Add specific  LST monitoring container

ctapipe_io_lst/containers.py
This PR is following a discussion on Drive reports and pointing positions at `cta-lstchain` https://github.com/cta-observatory/cta-lstchain/pull/153 with @FrancaCassol, @vuillaut and others.
@FrancaCassol Please have a look here if this is the way you want this in `LSTMonitoringContainer`. If not, suggest possible changes.
=> Adding LSTDriveContainer

ctapipe_io_lst/__init__.py
=> Make subarray a simple attribute in __init__

ctapipe_io_lst/__init__.py
Follow up from https://github.com/cta-observatory/cta-lstchain/issues/424
=> set obs_id to camera_config.configuration_id

ctapipe_io_lst/__init__.py
The u.ns was missing, this made trouble for the pulse integrators
=> Added missing units in the time step of the reference pulse shape

environment.yml, setup.py
Avoids an error with astropy 4.1
=> Require astropy 4.2

environment.yml, setup.py
Thanks to @maxnoe and the `protozfits` for realising a very quick fix for https://github.com/cta-observatory/cta-lstchain/issues/620
=> Force protozfits >2.0.1

ctapipe_io_lst/__init__.py
=> Better error message in case no files are give to MultiFile

ctapipe_io_lst/calibration.py, ctapipe_io_lst/tests/test_calib.py
Proper fix to the time lapse calibration integer underflow issue reported here #93
=> Fix underflow in timelapse calibration

ctapipe_io_lst/__init__.py
To address: https://github.com/cta-observatory/cta-lstchain/issues/684
=> Skip events with event_id==0

ctapipe_io_lst/__init__.py
See https://github.com/cta-observatory/cta-lstchain/pull/681
=> Update FF tagging defaults

ctapipe_io_lst/__init__.py, ctapipe_io_lst/calibration.py, ctapipe_io_lst/constants.py, ctapipe_io_lst/tests/test_calib.py, ctapipe_io_lst/tests/test_lsteventsource.py
Reading in gain selected R1 written the tool here: 
https://gitlab.cta-observatory.org/cta-array-elements/lst/subsystems/daq/offline_gain_selection
This now works.
Comparisons to before coming.
=> Implement support for already gain selected input data

.github/workflows/ci.yml, ctapipe_io_lst/__init__.py, ctapipe_io_lst/multifiles.py, ctapipe_io_lst/tests/test_lsteventsource.py, ctapipe_io_lst/tests/test_multifile.py, environment.yml, setup.py
Add context managers and move MultiFile to own module
* Add `__enter__`, `__exit__` and close methods to MultiFile
* Call `MultiFile.close` in `LSTEventSource.close`
=> Multifile fixes

.github/workflows/ci.yml, .gitignore, environment.yml, setup.py
Now changes required for the source!
=> Allow ctapipe 0.11 and test using it

ctapipe_io_lst/calibration.py, ctapipe_io_lst/tests/test_calib.py
Removes duplicated code by refactoring into a common function
=> Unify functions for spike positions and spike positions just before the ROI

example_stage1_config.json
To account for the new location of test files.
=> Fix stage1 json

ctapipe_io_lst/pointing.py
=> Fix issue with drive report and bending model tables not having the same length

.github/workflows/release-drafter.yml
The release draft was not updating fast / reliably, this should fix it
=> Add release drafter action

ctapipe_io_lst/__init__.py, ctapipe_io_lst/tests/test_stage1.py
As discussed here: https://github.com/cta-observatory/cta-lstchain/pull/950
=> Determine default for use_flatfield_heuristic by date

ctapipe_io_lst/__init__.py
=> Set events with both pedestal and calibration trigger bit to EventType.UNKNOWN

ctapipe_io_lst/__init__.py
The code before assumed that pixels marked as broken are not contained in the waveform array.
However, this is not the case for any current lst data as far as I know.
We either have:
* Module completely disconnected from EVB, essentially using a smaller camera with only working pixels
* Pixels marked as broken but still read out with garbage data in the array (very low values around ~200).
@moralejo @morcuended Is this correct? Or do we have to treat the third case of pixels marked as broken not being read out.
=> Change broken pixels treatment to work with files that include broken pixels in waveform

.zenodo.json
I could retrieve some ORCIDs using tributors
=> updating zenodo contributors ORCIDs using tributors

src/ctapipe_io_lst/__init__.py
The commas are not wanted, we want the implicit string concatenation, not a tuple of two strings
=> Fix helpstrings of traitlets

src/ctapipe_io_lst/calibration.py
This is needed for https://github.com/cta-observatory/cta-lstchain/pull/1017
=> Add public method to only update the last readout times without applying dt correction

src/ctapipe_io_lst/tests/test_lsteventsource.py
The assert was tautological...
=> Fix test assert

.github/workflows/ci.yml, environment.yml, setup.cfg, src/ctapipe_io_lst/__init__.py, src/ctapipe_io_lst/calibration.py, src/ctapipe_io_lst/compat.py, src/ctapipe_io_lst/tests/test_calib.py, src/ctapipe_io_lst/tests/test_cta_r1.py, src/ctapipe_io_lst/tests/test_lsteventsource.py
=> Add compatibility with ctapipe 0.21

setup.cfg
3.9 was already not tested anymore and dropped by protozfits
=> Raise python requirement to 3.10
